services:
  node:
    build: ./docker/node
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./web:/node/web
    working_dir: /node/web
  sendgrid:
    image: yudppp/simple-sendgrid-mock-server
    ports:
      - 3030:3030
    environment:
      - SENDGRID_API_KEY=SG.local
      - SESSION_COOKIE_SECRET=secret
